### ISSUE TITLE
custom faces with Aluminum Ice Pwnagotchi v1.7.9

### ISSUE THREAD

**Issue by eat-the-planet** [roodriiigooo/PWNAGOTCHI-CUSTOM-FACES-MOD#3]
I really love this mod. I am using a pi zero 2w with a V4 Wavshare 2.13 e-ink screen. I followed the directions but I couldn't get the faces to appear. copying the faces data into the config.toml file seemed to have something to do with the display not showing up correclty (after failing to have this work, i restored the backed-up files, but the screen would still not load properly.  after deleting the codes for the faces from the config.toml file, it worked fine

**Comment by roodriiigooo** [comment]
Hello!
It's hard to say what the problem might be because I'm not familiar with this version, and I don't have the same hardware you're using. However, I can imagine that this is caused by a missing variable or incorrect path in the configuration file. 

Please check if the mod entries in the widget are correct, and also make sure you're activating `ui.faces.png = true`.
The driver file for your screen can also interfere with the settings, it's another option to take a look at.

If works, tell me plz
